[ubuntu]
ubuntu1.my ansible_host=10.129.0.10 ansible_user=user1 ansible_port=22
ubuntu2.my ansible_host=10.129.0.11 ansible_user=user1 ansible_port=22

[centos]
centos1.my ansible_host=10.129.0.12 ansible_user=user1 ansible_port=22
